name: jaguar_jwt_lite
description: A starting point for Dart libraries or applications.
version: 1.1.0+0
repository: https://github.com/dsbferris/jaguar_jwt_lite

environment:
  sdk: ^3.7.0

# Add regular dependencies here.
dependencies:
  crypto: ^3.0.6

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
